version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - webnet
networks:
  webnet:
